version: '3.8'
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links: 
      - app

  app:
    container_name: app
    restart: always
    build: ./server 
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:root@localhost:5432/VerbumLern

  postgres:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=VerbumLern

volumes:
  pgdata: {}

